# -*- coding: utf-8 -*-
"""Linear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bEz1PnkNMZQv9aBD7TGNm-AHyjllG0_i
"""

# Linear-Regression - Prediction of Sell price of cars
# Soumen Dey (ref: youtube)

import pandas as pd
from io import StringIO
import io
import requests
import json
from io import FileIO
from json import loads, dumps
# import csv
import matplotlib.pyplot as plt

url = "https://raw.githubusercontent.com/Rimbik/ai-nextGen/refs/heads/main/linear_regression/CarData.csv"
s = requests.get(url).content
df = pd.read_csv(io.StringIO(s.decode('utf-8')))

plt.scatter(df['Milege'],df['SellPrice'])

plt.scatter(df['Age(yrs)'],df['SellPrice'])

X = df[['Milege','Age(yrs)']]
y = df['SellPrice']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=11)
# use random_state to have the same selection in the record set everytime you run.

X_train

y_train

X_test

y_test

len(X_train), len(y_train),len(X_test),len(y_test)

from sklearn.linear_model import LinearRegression
clf = LinearRegression()
clf.fit(X_train,y_train)
LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1)

X_test

y_test

clf.predict(X_test)

# Get Score/Correctness
clf.score(X_test,y_test)